---
blank_issues_enabled: false
contact_links:
  - name: BatchPDF-Creator Community Support
    url: https://github.com/miguerubsk/BatchPDF-Creator/discussions
    about: Please ask and answer questions here.
