name: Bash Formatting Check

on: [push, pull_request]

jobs:
  format:
    name: Check Bash Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install shfmt
        run: |
          curl -L -o shfmt "https://github.com/mvdan/sh/releases/latest/download/shfmt_linux_amd64"
          file shfmt  # Verifica que es un binario ejecutable
          chmod +x shfmt
          sudo mv shfmt /usr/local/bin/

      - name: Run shfmt
        run: /usr/local/bin/shfmt -d .
