name: Bash Formatting Check

on: [push, pull_request]

jobs:
  format:
    name: Check Bash Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install shfmt with Go
        run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run shfmt
        run: shfmt -d .

      - name: Debug shfmt
        run: |
          shfmt -version
          shfmt -d . || true  # Evita que el error detenga el workflow
