name: Format Check (shfmt)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install shfmt
        run: |
          curl -L https://github.com/mvdan/sh/releases/download/v3.4.0/shfmt_v3.4.0_linux_amd64 -o /usr/local/bin/shfmt
          chmod +x /usr/local/bin/shfmt

      - name: Check formatting and auto-correct
        run: |
          echo "Checking shell script formatting..."
          diff_output=$(shfmt -d .)
          if [ -n "$diff_output" ]; then
            echo -e "\033[31mFormatting issues detected!\033[0m"
            echo -e "\033[33mDifferences from standard formatting:\033[0m"
            echo "$diff_output"
            echo "Automatically fixing formatting..."
            shfmt -w .

            # Verificar si realmente se hicieron cambios
            if git diff --exit-code; then
              echo "No changes detected after auto-formatting."
              exit 0
            fi

            # Configurar credenciales de GitHub Actions para hacer commit
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"

            # Agregar y hacer commit de los cambios
            git add .
            git commit -m "Auto-format shell scripts" && git push || echo "Nothing to push"
          else
            echo "No formatting issues found."
          fi
