name: Format Check (shfmt)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install shfmt
        run: |
          curl -L https://github.com/mvdan/sh/releases/download/v3.4.0/shfmt_v3.4.0_linux_amd64 -o /usr/local/bin/shfmt
          chmod +x /usr/local/bin/shfmt

      - name: Check formatting
        run: |
          if ! shfmt -d .; then
            echo "Formatting errors detected!"
            exit 1
          fi
