---
name: Lint README.md

on:
  push:
    branches:
      - main
    paths:
      - README.md
  pull_request:
    paths:
      - README.md

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the current repo
        uses: actions/checkout@v3
      - name: Lint markdown files
        uses: nosborn/github-action-markdown-cli@master
        with:
          files: README.md
          config_file: ".markdownlint.json"
